odometry_converter:
  ros__parameters:
    # Frame IDs
    odom_frame_id: "odom"
    base_frame_id: "base_link"
    child_frame_id: "base_link"
    
    # Publishing rate (Hz)
    publish_rate: 10.0
    
    # Position covariance (x, y, z diagonal elements)
    position_covariance: [0.01, 0.01, 0.01]
    
    # Orientation covariance (roll, pitch, yaw diagonal elements)  
    orientation_covariance: [0.01, 0.01, 0.01]
    
    # Linear velocity covariance (x, y, z diagonal elements)
    linear_velocity_covariance: [0.01, 0.01, 0.01]
    
    # Angular velocity covariance (roll, pitch, yaw diagonal elements)
    angular_velocity_covariance: [0.01, 0.01, 0.01]
    
    # Velocity smoothing window size
    velocity_rolling_window_size: 5
    
    # Transform tolerance (seconds)
    transform_tolerance: 0.1
    
    # Scale factor for position (1.0 = no scaling)
    scale_factor: 1.0
    
    # Yaw conversion mode for coordinate frame transformation
    # Mode 0: ros_yaw = minecraft_yaw (no conversion)
    # Mode 1: ros_yaw = -minecraft_yaw (direction inversion) 
    # Mode 2: ros_yaw = minecraft_yaw + pi/2 (+90 degrees)
    # Mode 3: ros_yaw = minecraft_yaw - pi/2 (-90 degrees)
    # Mode 4: ros_yaw = minecraft_yaw + pi (+180 degrees)
    yaw_conversion_mode: 1